import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href="/profile" className={styles.card}>
            <h2>Profile &rarr;</h2>
            <p>View detailed profile information and projects.</p>
          </Link>

          <Link href="/resume" className={styles.card}>
            <h2>Resume &rarr;</h2>
            <p>Complete professional resume with experience and education.</p>
          </Link>

          <Link href="/chatbot" className={styles.card}>
            <h2>Chat &rarr;</h2>
            <p>Real-time messaging interface with Socket.io integration.</p>
          </Link>

          <Link href="/graphql" className={styles.card}>
            <h2>GraphQL Demo &rarr;</h2>
            <p>Explore GraphQL integration with Apollo Client.</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
